Update SrLatnMeTest.php
briannesbitt/Carbon pull request #2743
Opened 2023-01-01 21:21 UTC by perisicnikola37

2023-01-01 22:35 UTC, kylekatarnls commented
Thanks. 🙏 

Hello @milose @Glavic, invoking Serbian contributors 🧙 here to have a second look and if you can, please proceed the relevant changes on:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/sr_Latn_ME.php

2023-01-02 10:24 UTC, milose commented
Looks good to me @kylekatarnls, thanks @perisicnikola37

2023-01-02 10:29 UTC, milose commented
https://github.com/briannesbitt/Carbon/blob/1e60d1b9b3a445a6d450d960019a0a0c2f2a59d3/src/Carbon/Lang/sr_Latn_ME.php#L60 should be changed as per test.

2024-03-29 12:08 UTC, perisicnikola37 commented
@kylekatarnls Why this is still not merged?

2024-03-29 13:20 UTC, kylekatarnls commented
Hello @perisicnikola37 this is only a test file, that does not actually change the actual translations which live in:
https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/sr.php
+ the variants Cyrl and Latn

So if I merge this alone, actually test won't pass anymore and it will have no effect for users.

It would need now to change accordingly all language files and tests (if there are other countries that ME that are concerned).

2024-03-29 13:20 UTC, kylekatarnls approved these changes

2024-03-29 13:21 UTC, kylekatarnls requested changes
Source files need to be updated accordingly:

https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/sr.php

2024-03-29 13:21 UTC, kylekatarnls commented
I have another issue, I don't know why I cannot run the tests on this PR, maybe it needs to be rebased on last changes of master branch.

2025-01-23 06:25 UTC, closed without merging